<?php $_block = $this; ?>
<div id="<?php echo $_block->getHtmlId() ?>" >
    <div class="grid">
        <table cellspacing="0" class="data border" id="<?php echo $_block->getHtmlId() ?>_grid_ibannerz" width="100%">
            <col width="120" />
            <col />
            <col />
            <col />
            <col />
            <col />
            <col />
            <col />
            <col />
            <col />
            <col width="60" />
            <?php foreach ($_block->getImageTypes() as $typeId=>$type): ?>
            <?php endforeach; ?>
            <col width="50" />
            <col width="50" />
            <thead>
                <tr class="headings">
                    <th><?php echo Mage::helper('igallery')->__('Image') ?></th>
                    <th><?php echo Mage::helper('igallery')->__('Image Label') ?></th>
                    <th><?php echo Mage::helper('igallery')->__('Image Description') ?></th>
					<th><?php echo Mage::helper('igallery')->__('Image URL') ?></th>
                    <th><?php echo Mage::helper('igallery')->__('Shop URL') ?></th>
                    <th><?php echo Mage::helper('igallery')->__('Target For URL') ?></th>
					<th><?php echo Mage::helper('igallery')->__('Columns') ?></th>
					<th><?php echo Mage::helper('igallery')->__('Rows') ?></th>
					<th><?php echo Mage::helper('igallery')->__('Display Tab') ?></th>
					<th><?php echo Mage::helper('igallery')->__('Sort Order') ?></th>
                    <?php foreach ($_block->getImageTypes() as $typeId=>$type): ?>
                    <?php endforeach; ?>
                    <th><?php echo Mage::helper('igallery')->__('Video embeded') ?></th>
                    <th><?php echo Mage::helper('igallery')->__('Edit') ?></th>
                    <th><?php echo Mage::helper('igallery')->__('Disable') ?></th>
                    <th class="last"><?php echo Mage::helper('igallery')->__('Remove') ?></th>
                </tr>
            </thead>
            <tbody id="<?php echo $_block->getHtmlId() ?>_list">
                <tr id="<?php echo $_block->getHtmlId() ?>_template" class="template no-display">
                    <td class="cell-image"><div class="place-holder" onmouseover="<?php echo $_block->getJsObjectName(); ?>.loadImage('__file__')"><span><?php echo Mage::helper('igallery')->__('Roll Over for preview') ?></span></div><img src="<?php echo $this->getSkinUrl('images/spacer.gif')?>" width="100" style="display:none;" alt="" /></td>
                    <td class="cell-label"><input type="text" class="input-text" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
					<td class="cell-image-desc"><textarea style="width:100px" class="input-text" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')"></textarea></td>
                    <td class="cell-image-url"><input type="text" class="input-text" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
                    <td class="cell-shop-url"><input type="text" class="input-text" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
					<td class="cell-target-url">
                        <select onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" name="" id="">
                            <option value="0"><?php echo $this->__('Please Select') ?></option>
                            <option value="1"><?php echo $this->__('Current Window') ?></option>
                            <option value="2"><?php echo $this->__('New Window') ?></option>
                        </select>
                    </td>
                    <td class="cell-image-width">
						<select onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" name="" id="">
							<option value=""><?php echo $this->__('Please Select') ?></option>
							<option value="1">1</option>
							<option value="2">2</option>
							<option value="3">3</option>
							<option value="4">4</option>
							<option value="5">5</option>
							<option value="6">6</option>
						</select>
					</td>
					<td class="cell-image-height">
						<select onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" name="" id="">
							<option value=""><?php echo $this->__('Please Select') ?></option>
							<option value="1">1</option>
							<option value="2">2</option>
							<option value="3">3</option>
						</select>
					</td>
					<td class="display-in-show-tab">
						<select onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" name="" id="">
							<option value=""><?php echo $this->__('Please Select') ?></option>
							<option value="0"><?php echo $this->__('Lookbook') ?></option>
							<option value="1"><?php echo $this->__('Show-Tab') ?></option>
                            <option value="2"><?php echo $this->__('Backstage') ?></option>
						</select>
					</td>
					<td class="cell-position"><input type="text" class="input-text validate-number" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
                    <?php foreach ($_block->getImageTypes() as $typeId=>$type): ?>
                    <td class="cell-<?php echo $typeId ?> a-center" style="display:none;">
                        <input type="hidden" name="<?php echo $type['field'] ?>" onclick="<?php echo $_block->getJsObjectName(); ?>.setProductImages('__file__')" value="__file__" /></td>
                    <?php endforeach; ?>
                    <td class="cell-is-video a-center"><input type="checkbox" value="" onclick="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')"  /></td>
                    <td class="cell-edit a-center">
                        <input type="checkbox" onclick="" />
                        <input alt="__file__" id="forUrl" type="hidden" value=""  />
                        <input id="forFile" type="hidden" value=""  />
                    </td>
                    <td class="cell-disable a-center"><input type="checkbox" onclick="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
                    <td class="cell-remove a-center last"><input type="checkbox" onclick="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" /></td>
                </tr>

                <tr id="<?php echo $_block->getHtmlId() ?>-image-0">
                    <td class="cell-image"><?php echo Mage::helper('catalog')->__('No image') ?></td>
                    <td class="cell-label"><input type="hidden" />&nbsp;</td>
                    <td class="cell-position"><input type="hidden" />&nbsp;</td>
					<td class=""><input type="hidden" />&nbsp;</td>
                    <td class=""><input type="hidden" />&nbsp;</td>
					<td class=""><input type="hidden" />&nbsp;</td>
					<td class=""><input type="hidden" />&nbsp;</td>
					<td class=""><input type="hidden" />&nbsp;</td>
					<td class=""><input type="hidden" />&nbsp;</td>
                    <?php foreach ($_block->getImageTypes() as $typeId=>$type): ?>
                    <td class="cell-<?php echo $typeId ?> a-center" style="display:none;">
                        <input type="hidden" disabled="disabled" name="<?php echo $type['field'] ?>" onclick="<?php echo $_block->getJsObjectName(); ?>.setProductImages('no_selection')" value="no_selection" /></td>
                    <?php endforeach; ?>
                    <td class="cell-edit"><input type="hidden" />&nbsp;</td>
					<td class="cell-disable"><input type="hidden" />&nbsp;</td>
                    <td class="cell-remove"><input type="hidden" />&nbsp;</td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="100" class="last" style="padding:8px">
                        <?php echo $_block->getUploaderHtml() ?>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save" name="images" value="<?php echo $_block->htmlEscape($_block->getImagesJson()) ?>" />
<input type="hidden" id="smece_save" name="[smece]" value="smece" />
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save_image" name="[values]" value="<?php echo $_block->htmlEscape($_block->getImagesValuesJson()) ?>" />
<script type="text/javascript">
    //<![CDATA[
    var <?php echo $_block->getJsObjectName(); ?> = new Product.Igallery('<?php echo $_block->getHtmlId() ?>', <?php echo $_block->getUploader()->getJsObjectName() ?>, <?php echo $_block->getImageTypesJson() ?>);
    // var media_gallery_contentJsObject = new Product.Igallery('media_gallery_content', id_f4bddae9dca1b4cc80589dbce8108843_UploaderJsObject, {"gallery":{"label":"igallery","field":"igallery"}}); 
    //]]>
</script>

<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('td.cell-edit input').click(function() {
            if (jQuery(this).is(':checked')) {
                var file = jQuery(this).next('#forUrl').attr('alt');
                jQuery('input#forCheck').val('true');
                jQuery('input#fileUpdate').val(file);
            } else {
                jQuery('input#forCheck').val('false');
                jQuery('input#fileUpdate').val('');
            }
        })
    })
</script>