<?php
/**
 * @name         :  Apptha Out Of Stock Notification
 * @version      :  0.1.5
 * @since        :  Magento 1.4
 * @author       :  Apptha - http://www.apptha.com
 * @copyright    :  Copyright (C) 2011 Powered by Apptha
 * @license      :  http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date:  June 20 2011
 * @Modified By  :  Bala G
 * @Modified Date:  August 7 2013
 *
 * */
?>
<?php $_product = $this->getProduct();

$notifyMail  = Mage::getStoreConfig('Outofstocknotification/general/activate_apptha_outofstock_email');
$enableOutOfStock  = Mage::getStoreConfig('Outofstocknotification/general/activate_apptha_outofstock_enable');
$enableOutOfStock = intval($enableOutOfStock);
$notifyRequest = Mage::getStoreConfig('Outofstocknotification/general/activate_apptha_outofstock_notifymes');

$storeName = Mage::getStoreConfig("general/store_information/name");  
$_product = $this->getProduct();
$productId =  $_product->getId();

$productName = $_product->getName();


$productUrl = $_product->getUrlInStore();

$baseUrl     = Mage::getUrl('',array('_secure'=>true));
$crtlPageUrl = $baseUrl.'outofstocknotification/index/storeNotificationProductData';

?>

<?php if($_product->isSaleable()): ?>
<script type="text/javascript">
//<![CDATA[
    var bundle = new Product.Bundle(<?php echo $this->getJsonConfig() ?>);
//]]>
var crtlPageUrl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'outofstocknotification/index/storeNotificationProductData';   ?>';
Translator.add('AlreadyNotified','<?php echo $this->__('This Mail Id Already Notified'); ?>');
</script>
<?php endif; ?>
<?php if ($_product->isAvailable()): ?>
    <p class="availability in-stock"><?php echo $this->helper('catalog')->__('Availability:') ?> <span><?php echo $this->helper('catalog')->__('In stock') ?></span></p>
<?php else: ?>
    <p class="availability out-of-stock"><?php echo $this->helper('catalog')->__('Availability:') ?> <span><?php echo $this->helper('catalog')->__('Out of stock') ?></span></p>
<?php 
if($enableOutOfStock){
?>

<div class="block-body apptha-outofstock-block-body line" id='responceMesPlace'>
    <span id='contentofnotification' >
	   	 <div id="notify_conform" class="notify_conform"></div>
	     <span id="notify_message"><?php echo $notifyRequest; ?></span>
      <div id="padding_div" style="height: 33px;margin-top: 4px;" > 
	     <span id="notify_error" class="line notify_error"></span>
	     
	     <span id="notify_submit"> <b> <?php echo $this->__('Email')?> :</b>
	     <input id="outofstock_email" type="text"  name="outofstock_email"  >
	     <button class="button" title="Subscribe" type="submit" onclick="return stockNotifyValidate('<?php echo $productId; ?>','')" >
	     <span><span><?php echo $this->__('Notify Me'); ?></span></span>
	     </button> <div id='ajaximageshowing' class="ajaxreloadimage" ></div>
	     <div style="display: none;color: red;font-size: 11px;" id="outofstock_notify_error" > <?php echo $this->__('Please specify a valid Email Address'); ?><br></div>
	      </span>
	    
	</div>
	</span>
    
    <div class="powered_by">
          <?php echo $this->helper('outofstocknotification')->OutofStockKey(); ?>
      </div>
    
</div>
<?php } //if out of stock endable
    
 endif; ?>
<div class="price-box-bundle">
    <?php echo $this->getPriceHtml($_product) ?>
</div>
<?php echo $this->getChildHtml('bundle_prices') ?>

    <script type="text/javascript">

var crtlPageUrl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'outofstocknotification/index/storeNotificationProductData';   ?>';
Translator.add('AlreadyNotified','<?php echo $this->__('This Mail Id Already Notified'); ?>');

</script>